# Generated by Django 3.2.10 on 2024-06-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='fiber',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='total_carbohydrates',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
