# Generated by Django 3.2 on 2024-07-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_recipe_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='english_name',
            field=models.CharField(default='rice', max_length=255),
            preserve_default=False,
        ),
    ]
